/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCardGrid: typeof import('./components/business/activity/ActivityCardGrid.vue')['default']
    ActivityCreatorDialog: typeof import('./components/business/activity/ActivityCreatorDialog.vue')['default']
    ActivityDetailDrawer: typeof import('./components/business/activity/ActivityDetailDrawer.vue')['default']
    ActivityFiltersBar: typeof import('./components/business/activity/ActivityFiltersBar.vue')['default']
    ActivityScheduleBoard: typeof import('./components/schedule/ActivityScheduleBoard.vue')['default']
    ActivityScheduleDrawer: typeof import('./components/schedule/ActivityScheduleDrawer.vue')['default']
    ActivityTablePanel: typeof import('./components/business/activity/ActivityTablePanel.vue')['default']
    ApprovalTimeline: typeof import('./components/approval/ApprovalTimeline.vue')['default']
    BaseChart: typeof import('./components/charts/BaseChart.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MetricOverviewCard: typeof import('./components/business/dashboard/MetricOverviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
